### ISSUE TITLE
Input.gets not returning (only on devices with MIDI Input via USB?)

### ISSUE THREAD

**Issue by RyanScottLewis** [arirusso/midi-winmm#1] opened 2011-04-14 04:27 UTC
```
require 'midi-winmm'
require 'pp'

num_messages = 10

input_device = MIDIWinMM::Input.all.find { |d| d.instance_eval{@name} == "BCR2000" }
pp input_device # All good here.

input_device.open do |input|

  $>.puts "send some MIDI to your input now..."

  num_messages.times do
    m = input.gets
    $>.puts(m)
  end

end

$>.puts "finished"
```

Produces no output. Can't seem to get `MIDIWinMM::Input.gets` working for the life of me.

**Comment by arirusso** [comment] 2011-04-14 15:00
Just to make sure-- you're getting no output?  Not even "send some MIDI to your input now..." ?

**Comment by RyanScottLewis** [comment] 2011-04-14 15:05
No matter what the situation, MIDIWinMM::Input#gets will not capture any input.

**Comment by arirusso** [comment] 2011-04-14 15:15
Can you confirm that you're able to receive input in another program without changing your setup at all?

**Comment by RyanScottLewis** [comment] 2011-04-14 15:24
Sure can. I was just using the device in my DAW.
When I went to start playing around with `MIDIWinMM::Input` (until then I had just been using `Output`), it didn't work so I booted up Linux and tried `AlsaRawMIDI::Input` and it worked fine.

I've tried digging into your code to debug the problem but to no avail.

**Comment by arirusso** [comment] 2011-04-14 15:27
That's good to know but I'd like to hear that you can receive input in another Windows program-- in case there's an issue with your hardware driver or something else on the Windows system level.  Sorry, I know this is tedious and that may not even be the issue but I need to rule it out

**Comment by RyanScottLewis** [comment] 2011-04-14 15:30
Yeah, my DAW is FL Studio on Windows 7. I use it almost every day. =p

I just ran Glovepie script can easily access the device's I/O.

**Comment by arirusso** [comment] 2011-04-14 15:32
OK, thanks.  Are you using 32-bit or 64-bit Windows 7?

**Comment by RyanScottLewis** [comment] 2011-04-14 15:37
x64. I'll try to find a chance to try on a 32-bit machine.

Right now I don't even have any other machine to test it on =/

**Comment by arirusso** [comment] 2011-04-14 15:49
OK, that definitely could be the issue.  I wrote it and have only tested it on 32-bit.  The first place to look is at the data sizes of the C types that I used in the Map class.  I will have access to a 64 bit Win 7 laptop this weekend and I can work on it if you don't find the problem sooner

Off topic, but your Ubuntu install is also 64-bit, I assume?  Good to know that one is working.

**Comment by arirusso** [comment] 2011-04-14 16:10
Just a shot in the dark, you could try changing "DWORD = :ulong" to "DWORD = :int32" in the Map class

**Comment by RyanScottLewis** [comment] 2011-04-14 16:22
Same issue. 
Here's the error I'm getting: 

```
C:\Users\Ryguy\Desktop\omgomgomg> ruby bcr2000.rb
Input device:
#<MIDIWinMM::Input:0x267b4c0
 @id=1,
 @info=#<MIDIWinMM::Map::MIDIInputInfo:0x267b6d0>,
 @name="BCR2000",
 @type=:input>
-----------------------------------------------------------
send some MIDI to your input now...

!!! I tweak some knobs... push some buttons here...     !!!
!!! No response, so I press CTRL-C                      !!!

C:/Ruby192/lib/ruby/gems/1.9.1/gems/midi-winmm-0.1.0/lib/midi-winmm/input.rb:54:
in `join': Interrupt
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/midi-winmm-0.1.0/lib/midi-winmm
/input.rb:54:in `gets'
        from bcr2000.rb:155:in `<main>'

C:\Users\Ryguy\Desktop\omgomgomg> 
```

**Comment by arirusso** [comment] 2011-04-14 16:28
OK.  That's actually normal Control-C behavior.  

I'll try some things tomorrow, and let you know

**Comment by arirusso** [comment] 2011-04-18 01:41
I've tested on Windows 7 64-bit, and I'm a little frustrated to say that I didn't have any problems with input.  I'll adjust some of the C types to make sure we're in line with 32/64-bit porting best practices and all that.  If you have any other ideas for how I can help debug this let me know

**Comment by arirusso** [comment] 2011-04-18 15:16
I am closing this issue because I have it working on a Win 7 64-bit laptop (using a Roland UM-2 interface)

I am reasonably convinced that this is an issue with your hardware configuration.  My theory as to what is happening is that you don't necessarily have MIDI on your BCR2000 routed to the input that you're using with the app.  Just reading up on the BCR2000, I see that it has a MIDI-In jack-- which is where Input#gets is probably reading from in this case.  You may need to explicitly select the hardware controls on the BCR2000 as a separate input; enable some kind of merge option to route the controls to the input jack; or physically run a cable from one of the outputs to the input jack (this is what I do when using the UM-2).

**Comment by RyanScottLewis** [comment] 2011-04-18 15:22
The BCR2000 connects through USB. I can receive Input from it through MIDI-OX and several Python libraries this is most definitely a software bug. The input even works in alsa-rawmidi. In fact, this is the only library where I am unable to receive input from my device.

**Comment by arirusso** [comment] 2011-04-18 15:33
In the case of alsa-rawmidi it may be enumerating your hardware inputs differently because alsa does that in a very different way than the windows system libraries.  I mean, one clear possibility that I see is where you are using "d.instance_eval{@name} == "BCR2000"" to select the input... this could very likely be selecting your MIDI-In jack and not the USB connection. Just selecting on name == "BCR2000" is inexplicit because name isn't a unique property in Winmm. You could have 10 inputs with the same name (which is actually the case with some interfaces).  id is the only unique property

It certainly could be a bug but without more information about your setup I can't debug it.  I can walk you through supplying information if you like... Please copy and paste the output from MIDIWinMM::Device.all.inspect

**Comment by RyanScottLewis** [comment] 2011-04-18 15:44
No you don't understand. I have my BCR setup for USB only mode, which means if I were to connect anything to my MIDI-THRU on the BCR, neither the BCR or my computer would know it was connected. Also.. it's my only input device. Like I said, in multiple Python libraries on this Win 7 machine can receive input from the device.

[ #<MIDIWinMM::Input:0x2d87078
  @id=1,
  @info=#<MIDIWinMM::Map::MIDIInputInfo:0x2d87468>,
  @name="BCR2000",
  @type=:input>,
 #<MIDIWinMM::Output:0x2d85f08
  @id=2,
  @info=#<MIDIWinMM::Map::MIDIOutputInfo:0x2d86388>,
  @name="BCR2000",
  @type=:output>]

**Comment by arirusso** [comment] 2011-04-18 15:53
OK good, selecting isn't the issue... 

moving on, do you know if any of the python libraries or MIDI-OX are using winmm?  I would like to be convinced that this is not an issue between that BCR2000 usb routing setup and winmm.

**Comment by RyanScottLewis** [comment] 2011-04-18 16:09
I just noticed my last comment got screwed up with the formatting. 
But listen, don't even worry about it. I'm going to be trying to get this going and once I do, I'll clone your master branch and make the changes within my fork and add a pull request. The testing branch on my fork will never be merged into my master branch so don't mind the crazy changes from that branch. =p
Thanks for all your help, though!

Happy coding,
Ryan

**Comment by arirusso** [comment] 2011-04-18 16:22
Cool, well these hardware libs are always a pain to test and debug.  I'm happy to help and again, I can't say for sure that it's not a bug but there are so many unknowns (at least from my perspective) when it comes to the other libraries that you used, your hardware, etc that you probably are better off jumping in to it yourself

Again, I will adjust some of the C types in Map and maybe that will happen to fix this

**Comment by RyanScottLewis** [comment] 2011-04-18 18:26
Making some head way. After some tinkering with the data types, now when I use a virtual MIDI device like MIDI Yoke and emulate a Control Change midi-winmm can read it. Unfortunately, it segfaults when I try to open my BCR2000 input.

**Comment by arirusso** [comment] 2011-04-18 18:29
What happens if you use the master version of midi-winmm with the MIDI input jack on the BCR2000?

**Comment by RyanScottLewis** [comment] 2011-04-18 18:41
GOT IT! There were some issues as to how and when threads were being started/stopped. That and data type issues.

Later on I'm gonna find the needle in the hay within my testing branch and find out what specifically enabled my device's input to work.

**Comment by arirusso** [comment] 2011-04-18 18:53
OK, great.  Just do a pull request on a fresh branch once you've narrowed it down and I will test with the 3 hardware configurations that I have.  

Can you tell me, was MIDI Yoke working with the master version of the library?

**Comment by RyanScottLewis** [comment] 2011-04-18 18:58
Yup, MIDI Yoke works wonderfully. I made a little script that takes a cc value from a yoke input then doubles it and sends it to a yoke output. I can now make one knob in my DAW double the value of another (I could do that anyways, I was just bored =p)

**Comment by arirusso** [comment] 2011-04-18 19:02
I'm asking about the master version of midi-winmm 0.1.0-- MIDI Yoke alone works with that?

**Comment by RyanScottLewis** [comment] 2011-04-18 19:04
Yeah, thats why I was so confused as to why my BCR wasn't working... very strange.

Right now input from my BCR works only under my testing branch, while is Yoke working with both.

**Comment by arirusso** [comment] 2011-04-18 19:17
Gotcha, thanks! 

Just trying to get more of an idea of why this might be happening.

If you have time, try testing both versions with your DAW's MIDI input jack-- just for the sake of thoroughness.  You can probably just send a cable from out to in...

That would suggest that this is an issue that comes up when MIDI/USB routing is present

**Closed as completed** 2011-04-20 01:50 UTC
